"use client"
import React from "react";
import Gallery from "../../../../../../common/molecules/gallery/Gallery";
import GalleryItem from "../../../../../../common/atoms/galleryItem/GalleryItem";

const SingleQuestPage = () => {
  return (
    <div>
      <h2 className="text-lg font-medium ml-2 mt-5"> Galería de la misión </h2>
      <Gallery>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem><GalleryItem
        imgSrc={"https://picsum.photos/800/600"}
        imgCaption={"hola-mundo"}
      ></GalleryItem>
      <GalleryItem
        imgSrc={"https://picsum.photos/800/600"}
        imgCaption={"hola-mundo"}
      ></GalleryItem>
      <GalleryItem
        imgSrc={"https://picsum.photos/800/600"}
        imgCaption={"hola-mundo"}
      ></GalleryItem>
      <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem><GalleryItem
        imgSrc={"https://picsum.photos/800/600"}
        imgCaption={"hola-mundo"}
      ></GalleryItem>
      <GalleryItem
        imgSrc={"https://picsum.photos/800/600"}
        imgCaption={"hola-mundo"}
      ></GalleryItem>
      <GalleryItem
        imgSrc={"https://picsum.photos/800/600"}
        imgCaption={"hola-mundo"}
      ></GalleryItem>
      <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>

<GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
        <GalleryItem
          imgSrc={"https://picsum.photos/800/600"}
          imgCaption={"hola-mundo"}
        ></GalleryItem>
      </Gallery>
    </div>
  );
};

export default SingleQuestPage;
